<?php

namespace App\Helpers\FakeProviders;

class DesignTagEventFakeProvider extends \Faker\Provider\Base
{
    private $list = [
        "20's",
        "60's",
        "70's",
        "80's",
        "90's",
        "Alumnae/Alumni",
        "American/USA",
        "Anchor",
        "Animal Print",
        "Animal",
        "Anniversary",
        "Army/Military/Camo",
        "Arrowspike",
        "Athletic/Sports/Intramurals",
        "Bachelorette/Wedding",
        "Ballet",
        "Band Party",
        "Banquet",
        "Barn/Western/Hay Ride",
        "Beach",
        "Boat/Riverboat/Cruise/Nautical",
        "Bows/Ties",
        "Breast Cancer/Make-a-Wish",
        "Brotherhood",
        "Business/Corporate",
        "Camps and Clubs",
        "Carnival",
        "Carnval Games",
        "Casino/Vegas",
        "Chevron",
        "Church/Religious",
        "Circus",
        "Classic Rock",
        "Crest/Shield/Symbols",
        "Crush/Krush",
        "Dance",
        "Disney",
        "Easter",
        "Executive Board",
        "Fall",
        "Family Weekend",
        "Floral",
        "Foil",
        "Food",
        "Food Function",
        "Fraternity",
        "Game/Trivia Night",
        "Geometric",
        "Go Greek/Greek Week/Greek Weekend",
        "High School",
        "Hippie",
        "Holiday",
        "Hollywood",
        "Home",
        "House",
        "Infinity",
        "Just for Fun",
        "Love",
        "Luau",
        "Mai Tai",
        "Mandalas",
        "Mardi Gras/Masquerade",
        "Mascot",
        "Metallic",
        "Mexican",
        "Midwest",
        "Movies/TV Theme",
        "Mud Wrestling",
        "Music",
        "Natural",
        "Neon",
        "Original Paterns",
        "Pagent",
        "Palm Tree",
        "Pancake Party",
        "Panhellenic",
        "Patriotic",
        "Picnic",
        "Pineapple",
        "Pledge",
        "Pocket Stickers",
        "Powderpuff",
        "PR",
        "Preppy",
        "Presents",
        "Retro/Neon",
        "Rose Ball",
        "School Spirit",
        "Seniors",
        "Shamrock",
        "Sib's Weekend",
        "Simple",
        "Sisterhood",
        "Skulls",
        "Southern",
        "Spring",
        "Spring Fling",
        "State Designs/Greek",
        "State Designs/Maps",
        "State Specific",
        "Streetwear",
        "Stripes",
        "Summer",
        "Talent Show",
        "Tie Dye",
        "Toga",
        "Tribal",
        "Tropical",
        "Vintage",
        "Watermelon",
        "Watermelon Bust",
        "Western",
        "Wing Fling",
        "Winter",
        "Winter Holidays",
        "Wish Week",
        "Woolly Threads",
        "Wreath",
    ];

    public function design_tag_event()
    {
        return $this->list[rand(0, count($this->list) - 1)];
    }
}