<?php

namespace App\Helpers\FakeProviders;

class DesignTagChapterFakeProvider extends \Faker\Provider\Base
{
    private $list = [
        "Kappa Delta",
        "Alpha Delta Phi",
        "Delta Delta Delta",
        "Delta Sigma Theta",
        "Sigma Delta Tau",
        "Delta Sigma Pi",
        "ALPHA CHI OMEGA",
        "ALPHA XI DELTA",
        "ALPHA EPSILON PHI",
        "CHI OMEGA",
        "DELTA GAMMA",
        "PHI MU",
        "Alpha Epsilon Pi",
        "Alpha Sigma Phi",
        "Delta Chi",
        "Delta Tau Delta",
        "Lamba Chi Alpha",
        "Sigma Phi Epsilon",
        "Zeta Beta Tau",
        "Delta Zeta",
        "Sigma Kappa",
        "Kappa Delta Rho",
        "Lambda Chi Alpha",
        "Pi Kappa Alpha",
        "Tau Kappa Epsilon",
        "Alpha Delta Pi",
        "Alpha Phi",
        "Zeta Tau Alpha",
        "Sigma Alpha Epsilon",
        "Alpha Tau Omega",
        "Kappa Sigma",
        "Delta Chi Home",
        "Phi Gamma Delta",
        "Delta Sigma Phi (Colony)",
        "Phi Kappa University",
        "Theta Chi",
        "Alpha Gamma Delta",
        "Alpha Omicron Pi",
        "Sigma Chi",
        "Sigma Pi",
        "Alpha Phi Alpha",
        "Phi Lambda Chi",
        "Theta Phi Alpha",
        "Phi Delta Theta",
        "Phi Kappa Psi",
        "Kappa Alpha Theta",
        "Kappa Kappa Gamma",
        "Alpha Gamma Rho",
        "Alpha Psi",
        "Beta Theta Pi",
        "Chi Phi",
        "Delta Kappa Epsilon",
        "Delta Sigma Phi",
        "Farmhouse",
        "Kappa Alpha Order",
        "Phi Kappa Tau",
        "Phi Sigma Kappa",
        "Pi Kappa Phi",
        "Sigma Nu",
        "Sigma Tau Gamma",
        "Theta Xi",
        "Alpha Sigma Alpha",
        "Kappa Alpa Psi",
        "Omega Psi Phi",
        "Zeta Phi Beta",
        "Alpha Kappa Alpha",
        "Pi Lambda Phi",
        "Gamma Phi Omega Sorority",
        " Inc.",
        "Gamma Rho Lambda",
        "Pi Beta Phi",
        "Phi Mu Alpha",
        "Alpha Delta Pi",
        "",
        "Kappa Kappa Gamma",
        "",
        "Zeta Tau Alpha",
        "",
        "Phi Iota Alpha",
        "Phi Sigma Sigma",
        "Alpha Gamma Pi",
        "Tau Epsilon Phi",
        "Alpha Pi Sigma",
        "Lambda Theta Alpha",
        "Sigma Lambda Gamma",
        "Alpha Kappa Delta Phi",
        "Gamma Phi Beta",
        "Delta Lambda Phi",
        "Alpha Epsilon Pi (AE_)",
        "Delta Upsilon",
        "Delta Phi Epsilon",
        "Kappa Beta Gamma",
        "Sigma Alpha Mu",
        "Xi Kappa",
        "Theta Delta Chi",
        "delta Delta Phi Zeta",
        "Zeta Chi Omega",
        "Sigma Gamma Rho",
        "Chi Sigma Phi",
        "Lambda Theta Nu",
        "Sigma Lambda Beta",
        "Lambda Theta Phi",
        "Gamma Zeta Alpha",
        "Phi Lambda Rho",
        "Delta Lambda Chi",
        "Rho Delta Chi",
        "Tau Omega Rho",
        "Alpha Sigma Tau",
        "Alpha Kappa Lambda",
        "Sigma Alpha Omega",
        "Omega Zeta Theta",
        "Pi Phi Epsilon",
        "Sigma Alpha Beta",
        "Lambda Phi Epsilon",
        "Carnegie Mellon University",
        "Phi Sigma Rho",
        "Sigma Psi",
        "Zeta Psi",
        "Gamma Nu Delta",
        "Lambda Pi Chi",
        "Sigma Rho Phi",
        "Iota Nu Delta",
        "Phi Beta Sigma",
        "Kappa Delta Chi",
        "Alpha Chi Rho",
        "Omicron Pi Omicron",
        "Phi Kappa Sigma",
        "Zeta Nu",
        "Beta Upsilon Chi",
        "Chi Psi",
        "Triangle",
        "Kappa Kapppa Gamma",
        "Delta Phi",
        "Kappa Alpha",
        "Alpha Delta Chi",
        "Alpha Sigma Kappa",
        "Kappa Delta Chi Sorority",
        "Lambda Theta Nu Sorority",
        "Sigma Alpha",
        "Alpha Gamma Omega",
        "Phi Kappa Theta",
        "ACACIA",
        "Alpha Phi Delta",
        "Sigma Chi__",
        "Phi Gamma Delta (FIJI)",
        "Chi Upsilon Sigma Latin",
        "Delta Phi Omega",
        "Kappa Phi Gamma",
        "Sigma Sigma Sigma",
        "Alpha Phi Alpha Fraternity",
        "Beta Theta Pi Fraternity",
        "Delta Epsilon Psi Fraternity",
        "Alpha Delta",
        "Gamma Phi",
        "Lota Phi Theta",
        "Alpha Phi",
        "",
        "Mu Sigma Upsilon",
        "Kappa Alpha Psi",
        "Omega Delta Phi",
        "Lambda Tau Omega",
        "Lambda Pi Upsilon",
        "Lambda Kappa Sigm",
        "Iota Phi Theta",
        "Alpha Nu Omega Sorority",
        "Delta Sigma ThetaXi Epsilon",
        "Phi Mu kappa Rho",
        "Sigma Gamma Rho Sorority",
        "Zeta Phi Beta Sorority",
        " Pi Eta",
        "Alpha Nu Omega Fraternity",
        "Kappa Alpha Psi Fraternity",
        "Lambda Theta Phi Fraternity",
        "Phi Mu Alpha Sinfonia",
        "Phi Mu Delta",
        "ALPHA OMEGA EPSILON",
        "Psi Upsilon",
        "Triangle Fraternity",
        "Alpha Theta Beta",
        "Acacia Fraternity",
        "Kappa Sigma Fraternity",
        "Phi Delta Theta Fraternity",
        "Phi Kappa Psi Fraternity",
        "Phi Kappa Tau Fraternity",
        "Phi Mu Delta Fraternity",
        "Sigma Chi Fraternity",
        "Sigma Pi Fraternity",
        "Alpha Epsilon Ph",
        "Alpha PI",
        "Phi Beta Phi",
        "Beta Sigma Psi",
        "Sigma Beta Rho",
        "Sigma Phi Beta",
        "Gamma Eta",
        "Alpha Chi Omega - Delta Nu",
        "Alpha Omicron Pi - Iota Sigma",
        "Sigma Alpha Epsilon Pi",
        "Sigma Phi Delta",
        "Delta Xi Phi",
        "Alpha Theta Alpha",
        "Sigma Phi Lambda",
        "Gamma Psi",
        "Kappa Lambda Psi",
        "Delta Psi / No.6",
        "Kappa Sigma Gamma Pi",
        "Nu Delta",
        "Phi Beta Epsilon",
        "Phi Alpha Mu",
        "Alpha Kappa Psi",
        "Alpha Delta Alpha",
        "Phi Delta Chi",
        "Theta Chi Epsilon",
        "Kappa Delta Psi",
        "Xi Omicron Iota",
        "Alpha Gamma Sigma",
        "Tau Delta Phi",
        "Alpha Sigma PhiMichael Filosa",
        "Alpha Phi Omega",
        "Sigma Psi Kappa",
        "Kappa Xi Kappa",
        "Kappa Alpha Order*",
        "Sigma Pi*",
        "Kappa Psi",
        "Alpha Kappa Sigma",
        "Delta Chi Lambda",
        "Gamma Alpha Omega",
        "FIJI",
        "Sigma Lambda Sigma",
        "OMEGA DELTA",
        "PHI KAPPA PSI",
        "",
        "Alpha Chi Omega Sorority",
        "Delta Gamma Fraternity",
        "Chi Omega Fraternity",
        "Gamma Phi Beta Sorority",
        "Delta Delta Delta Fraternity",
        "Evans Scholars",
        "Farm House",
        "FIJI/Phi Gamma Delta",
        "Sigma Omicron Pi",
        "Alpha Rho Chi",
        "Alpha Gmma Delta",
        "Beta Chi Theta",
        "Beta Kappa Sigma",
        "Chi Upsilon Sigma",
        "Omega Phi Beta",
        "Gamma Phi Omega",
        "Omega Phi Kappa",
        "Ceres",
        "Omega Zeta Pi",
        "Beta Mu Sigma",
        "Lambda Alpha Upsilon",
        "Kappa Delta Phi",
        " NAS Sorority",
        "Phi Delta Beta",
        "Delta Psi Omega",
        "Sigma Sigma Chi",
        "Zeta Phi",
        "Kappa Delta Omega",
        "Theta Alpha Omega",
        "Alpha Kappa Phi",
        "Sigma Iota Alpha",
        "Sigma Lambda Upsilon",
        "Lambda Upsilon Lambda",
        "Pi Alpha Nu",
        "Lambda Sigma Upsilon",
        "Pi Delta Chi",
        "Sigma Gamma Phi",
        "Alpha Delta Eta",
        "Omicron Xi",
        "Phi Lambda Phi",
        "Psi Phi Gamma",
        "Sigma Tau Chi",
        "Zeta Chi Zeta",
        "Mu Beta Psi",
        "Theta Alpha Lambda",
        "Theta Nu Xi",
        "Theta Gamma",
        "Alpha Gamma Delta Sorority",
        "Alpha Xi Delta Sorority",
        "Delta Phi Epsilon Sorority",
        "Phi Sigma Sigma Sorority",
        "Alpha Tau Omega Fraternity",
        "Pi Kappa Alpha Fraternity",
        "Theta Chi Fraternity",
        "Lambda Chi Alpha",
        "SIGMA EPSILON",
        "Delta Epsilon Psi",
        "Phi Alpha Delta",
        "Alpha Sigma Rho",
        "Sigma Phi Omega Sorority",
        " Inc.",
        "Zeta Phi Beta Sorority",
        " Inc.",
        "Phi Iota Alpha Fraternity",
        " Inc",
        "Sigma Kappa Phi",
        "Sigma Chi Omega",
        "Lone Star",
        "Lambda Sigma Phi",
        "Phi Beta Chi",
        "Alpha Delta Chi",
        "",
        "Phi Sigma Rho",
        "",
        "Sigma Alpha Mu**",
        "Alpha Epsilon Pi Chi Upsilon",
        "Alpha Sigma Phi Pi",
        "Chi Psi Psi Delta",
        "Phi Kappa Tau Psi",
        "Pi Kappa Phi Eta Gamma",
        "Zeta Beta Tau Beta Alpha Theta",
        "_appa Sigma",
        "Alpha Psi Lambda",
        "Chi Sigma Tau",
        "Sigma Phi Dleta",
        "Chi Sigma Omega",
        "Lambda Zeta Chi",
        "Pi Kappa Alpha (colony)",
        "Kappa Delta Phi NAS",
        "AlphaDelta Pi",
        "Alpha Epsion Pi",
        "Omega Phi Psi",
        "Phi Kappa Phi",
        "Iota Delta Nu",
        "Sigma Phi Rho",
        "Phi Sigma Phi",
        "Lambda Delta Phi",
        "Chi Psi (ÒLodgeÓ)",
        "Delta Psi",
        "Nu Alpha Kappa",
        "Alpha Phi Gamma",
        "Omega Delta sigma",
        "Chi Kappa Rho",
        "Kappa Gamma Rho",
        "Kappa Kappa Gamm",
        "Alpha Epsilon Pi (AEPi)",
        "Alpha Sigma Phi (Alpha Sig)",
        "Alpha Tau Omega (ATO)",
        "Beta Theta Pi (Beta)",
        "Chi Psi (The Lodge)",
        "Delta Kappa Epsilon (DKE)",
        "Delta Sigma Phi (Delta Sig)",
        "Delta Upsilon (DU)",
        "Kappa Alpha Order (KA)",
        "Kappa Sigma (Kappa Sig)",
        "Lambda Chi Alpha (Lambda Chi)",
        "Phi Delta Theta (Phi Delt)",
        "Phi Gamma Delta (Phi Gam)",
        "Pi Kappa Alpha (PiKA)",
        "Pi Kappa Phi (Pi Kapp)",
        "Pi Lambda Phi (Pi Lam)",
        "Sigma Alpha Epsilon (SAE)",
        "Sigma Phi",
        "Sigma Phi Epsilon (Sig Ep)",
        "Zeta Beta Tau (ZBT)",
        "Zeta Psi (Zete)",
        "Alpha Delta Pi (ADPi)",
        "Delta Chi Fraternity",
        "Delta Tau Delta (Delts)",
        "Sigma Omega",
        "Sigma Mu Omega",
        "Alpha Delta Phi Society",
        "Delta Phi--St Elmo's Club",
        "ZETA SIGMA CHI",
        "Beta Theta Phi",
        "Alpha Omricon Pi",
        "Kappa Delta Phi",
        "Delta Xi Nu",
        "Delta Beta Chi",
        "Delta Theta Sigma",
        "Kappa Tau",
        "Kappa Alpha Sigma",
        "Sigma Alpha Iota",
        "Phi Sigma",
        "Alpha Sigma",
        "Phi Chi Epsilon",
        "Iota Gamma Upsilon",
        "Alpha Tau Gamma",
        "Pi Kappa Alpha (PIKE)",
        "Psi Sigma Phi",
        "Pi Alpha Phi",
        "Kappa Delta Sorority",
        "Sigma Psi Zeta",
        "Alpha Gamma Rho Fraternity",
        "Lamda Chi Alpha",
        "Alpha Epsilon Phi__",
        "__Alpha Omicron Pi_",
        "Alpha Phi_",
        "_Chi Omega",
        "_Delta Gamma",
        "Pi Beta Phi__",
        "Alpha Epsilon Pi_",
        "_Theta Xi",
        "Omega Psi Ch",
        "Sigma Gamma Rho Sorority",
        " Inc.",
        "Alpha Epsilon Pi (colony)",
        "Phi Gamma Delta (colony)",
        "Delta Kappa Theta",
        "Theta Nu Xi Multicultural",
        "Gamma Sigma Sigma",
        "Beta Phi Omega",
        "TBD",
        "Epsilon Kappa Theta",
        "Kappa Delta Epsilon",
        "Alpha Chi Alpha",
        "Beta Alpha Omega",
        "Bones Gate",
        "Chi Gamma Epsilon",
        "Chi Heorot",
        "Gamma Delta Chi",
        "Kappa Kappa Kappa",
        "Phi Delta Alpha",
        "Delta Phi Mu",
        "Theta Xi Fraternity",
        "Delta Sigma P",
        "Theta Pi",
        "Theta Tau",
        "Pi Kappa Tau",
        "Epsilon Omega",
        "Kappa Phi",
        "Delta Epsilon",
        "Iota Iota",
        "Psi Zeta",
        "Alpha Kappa Delti Phi",
        "Gamma Rho",
        "Tri Sigma",
        "Gamma Xi",
        "Epsilon Rho",
        "Gamma Beta",
        "Epsilon Zeta",
        "Alpha Kappa",
        "Phi Delta Epsilon",
        "Alpha Delta P",
        "Tri Delta",
        "Alpha Omicron P",
    ];

    public function design_tag_chapter()
    {
        return $this->list[rand(0, count($this->list) - 1)];
    }
}