<?php

namespace App\Helpers\FakeProviders;

class DesignTagCollegeFakeProvider extends \Faker\Provider\Base
{
    private $list = [
        "University of Illinois",
        "Pennsylvania State Univeristy",
        "Purdue Univeristy",
        "Virginia Tech University",
        "Cornell University",
        "Indiana University-Bloomington",
        "University of Michigan",
        " Ann Arbor",
        "University of Alabama",
        "Auburn University",
        "University of Florida",
        "Florida State University",
        "University of Virginia",
        "Miami University-Oxford",
        "University of Georgia",
        "University of Maryland",
        "University of Washington-Seattle",
        "University of Missouri",
        "Arizona State University",
        "Georgia Institute of Technology",
        "Rutgers University",
        "University of California",
        " Berkley",
        "University of Arizona",
        "The University of Texas at Austin",
        "University of Pennsylvania",
        "University of Wisconsin-Madison",
        "University of Nebraska-Lincoln",
        "University of Kentucky",
        "Iowa State University",
        "University of Minnesota",
        "North Carolina State University",
        "Syracuse University",
        "Michigan State University",
        "University of Central Florida",
        "Texas A & M University-College Station",
        "University of Kansas",
        "University of North Carolina at Chapel Hill",
        "Texas Tech University",
        "University of California",
        " Los Angeles",
        "The University Of Tennessee Knoxville",
        "Louisiana State University",
        "Kansas State University",
        "University of Delaware",
        "Oregon State University",
        "Oklahoma State University",
        "Washington State University",
        "Vanderbilt Unversity",
        "University of Oklahoma",
        "Bowling Green State University",
        "University of South Carolina",
        "James Madison University",
        "University of Southern California",
        "University of South Florida",
        "San Diego State University",
        "Northwestern University",
        "Clemson University",
        "University of Cincinnati",
        "University of Mississippi",
        "Illinois State Univeristy",
        "Case Western Reserve University",
        "George Washington University",
        "Virginia Commonwealth University",
        "Univeristy of Arkansas",
        "University of North Texas",
        "Stephen F Austin State University",
        "Rensselaer Polytechnic Institute",
        "West Virginia University",
        "University of California",
        " Davis",
        "Ohio University",
        "University of Colorado Boulder",
        "Buffalo State",
        " The State University of New York",
        "Georgia Southern University",
        "Mississipi State university",
        "College of William & Mary",
        "University of Houston",
        "Baylor University",
        "University of Iowa",
        "Northern Illinois University",
        "University of Connecticut",
        "University of Miami",
        "East Carolina University",
        "Western Kentucky University",
        "University of Oregon",
        "Kent State University",
        "Lehigh University",
        "Florida International University",
        "University of North Carolina at Charlotte",
        "Missouri State University",
        "Washington University in St Louis",
        "University of Idaho",
        "Texas Christian University",
        "Western Michigan University",
        "University of Pittsburgh-Pittsburgh Campus",
        "College of Charleston",
        "Middle Tennessee State University",
        "University of North Carolina at Willmington",
        "Radford University",
        "Eastern Kentucky University",
        "Northwestern Missouri State University",
        "Southeast Missouri State University",
        "California State University",
        " Long Beach",
        "Western Illinois University",
        "Towson University",
        "University of Southern Mississippi",
        "University of Louisville",
        "Ball State University",
        "American University",
        "University of Rochester",
        "Tulane University",
        "Appalachian State University",
        "University of Nevada",
        " Las Vegas",
        "University of Toledo",
        "Colorado State University",
        "University of Rhode Island",
        "Florida Atlantic University",
        "University of Memphis",
        "Texas State University-San Marcos",
        "Temple University",
        "Drexel University",
        "Massachusetts Institute of Technology",
        "University of West Georgia",
        "California State University",
        " Sacramento",
        "San Jose State University",
        "The University of Texas at San Antonio",
        "Southern Methodist University",
        "Indiana State University",
        "Central Michigan University",
        "Eastern Michigan University",
        "Villanova University",
        "Boston University",
        "University at Buffalo",
        " The State University of New York",
        "Valdosta State University",
        "Western Carolina University",
        "George Mason University",
        "University of Central Missouri",
        "California State University",
        " Northridge",
        "Sam Houston State University",
        "West Chester University of Pennsylvania",
        "Indiana University of Pennsylvania",
        "University of Louisiana",
        "Longwood University",
        "The University of Texas at Arlington",
        "University of Wisconsin",
        " Oshkosh",
        "University of Chicago",
        "Bradley University",
        "Ferris State University",
        "University of Akron Main Campus",
        "Shippensburg University of Pennsylvania",
        "University of Maine",
        "The College of New Jersey",
        "Johns Hopkins University",
        "Troy Univeristy",
        "University of North Florida",
        "Murray State University",
        "University of Dayton",
        "Universtiy of Massachusetts Amherst",
        "Rowan University",
        "University of Alabama",
        " Birmingham",
        "University of South Alabama",
        "Georgia State University",
        "Emory University",
        "Morehead State University",
        "Arkansas State University",
        "Northern Arizona University",
        "Souther Illinois University Carbondale",
        "Carnegie Mellon University",
        "New York University",
        "Richard Stockton College of New Jersey",
        "Kennesaw State University",
        "Southeastern Louisiana University",
        "California State University",
        " Fullerton",
        "Texas A & M University-Commerce",
        "New Mexico State University",
        "Wichita State University",
        "Pittsburg State University",
        "University of North Dakota",
        "DePaul University",
        "Wayne State University",
        "Duquesne University",
        "Edinboro University",
        "Northeastern University",
        "Stony Brook University",
        "Columbia University",
        "Seton Hall University",
        "Georgia College & State University",
        "Northwestern State University of Louisiana",
        "University of North Carolina at Greensboro",
        "Christopher Newport University",
        "Northern Kentucky University",
        "Missouri University of Science and Technology",
        "Lamar University",
        "Drake University",
        "Indiana University-Purdue University-Indianapolis",
        "Grand Valley State University",
        "California University of Pennsylvania",
        "University of New Hampshire",
        "McNeese State University",
        "Univeristy of Richmond",
        "San Francisco State University",
        "Eastern Washington University",
        "University of Wisconsin",
        " Whitewater",
        "University of Illinois at Chicago",
        "Southern Illinois University Edwardsville",
        "Wright State Univeristy",
        "Worcester Polytechnic Institute",
        "Rutgers University Newark",
        "Kean University",
        "Ramapo College of New Jersey",
        "University of Maryland",
        " Baltimore County",
        "University of Nevada",
        " Reno",
        "The University of Texas at Dallas",
        "University of Nebraska",
        " Omaha",
        "Loyola University Chicago",
        "Michigan Technological University",
        "Hofstra University",
        "Adelphi University",
        "Rutgers University Camden",
        "Fairleigh Dickinson University",
        " Metropolitan",
        "Austin Peay State University",
        "University of Missouri",
        " Kansas City",
        "Loyola Marymount University",
        "Tarleton State University",
        "North Dakota State University",
        "Butler University",
        "Cleveland State University",
        "Youngstown State University",
        "University of Northern Colorado",
        "Yale University",
        "University of Hartford",
        "State University of New York at Plattsburg",
        "Louisiana Tech University",
        "University of New Orleans",
        "Boise State University",
        "University of Utah",
        "Emporia State University",
        "Creighton University",
        "University of South Dakota",
        "University of Wisconsin-Milwaukee",
        "Valparaiso University",
        "Baldwin Wallace University",
        "University of Wyoming",
        "Tufts University",
        "New Jersey Institute of Technology",
        "Frostburg State University",
        "Wofford College",
        "University of Arkansas at Little Rock",
        "Pepperdine University",
        "University of New Mexico",
        "University of Tulsa",
        "Robert Morris University",
        "University of Michigan-Dearborn",
        "University of Vermont",
        "State University of New York at Old Westbury",
        "State University of New York at Oswego",
        "Monmouth University",
        "Stevens Institute of Technology",
        "Salisbury University",
        "Henderson State University",
        "The University of Texas at El Paso",
        "University of Central Oklahoma",
        "Minnesota State University",
        " Mankato",
        "University of Souther Indiana",
        "Oakland University",
        "Fairleigh Dickinson University",
        " College at Florham",
        "Florida Gulf Coast University",
        "University of North Georgia",
        "University of Central Arkansas",
        "University of Arkansas at Monticello",
        "Texas A & M University-Corpus Christi",
        "Prairie View A & M University",
        "Washburn University",
        "University of Nebraska Kearney",
        "South Dakota State University",
        "Marquette University",
        "Saginaw Valley State University",
        "University of Detroit Mercy",
        "University of Montana",
        "Montana State University",
        "Widener University",
        "Bentley University",
        "Sacred Heart University",
        "State University of New York at New Paltz",
        "Rider University",
        "Missouri Western State University",
        "Texas Southern University",
        "North Eastern State University",
        "University of Wisconsin",
        " Platteville",
        "Capital University",
        "Lock Haven University",
        "Brown University",
        "Clarkson University",
        "Virginia State University",
        "Norfolk State University",
        "West Virginia Wesleyan College",
        "California State University",
        " Los Angeles",
        "The University of Texas-Pan American",
        "Texas A & M University-Kingsville",
        "University of the Incarnate Word",
        "West Texas A & M University",
        "University of Northern Iowa",
        "Lewis University",
        "Indiana University-Southeast",
        "Ashland University",
        "East Stroudsburg University of Pennsylvania",
        "La Salle University",
        "State University of New York College at Cortland",
        "New Jersey City University",
        "Florida Agricultural and Mechanical University",
        "Virginia Wesleyan College",
        "Arkansas Tech University",
        "Drury University",
        "Oklahoma City University",
        "Fort Hays State University",
        "Baker University",
        "University of Wisconsin",
        " River Falls",
        "Roosevelt University",
        "Colorado School of Mines",
        "Howard University",
        "University of New Haven",
        "Marist College",
        "University of Maryland Eastern Shore",
        "University of Virginia",
        " Wise",
        "Hampton University",
        "University of Arkansas-Fort Smith",
        "University of Missouri St. Louis",
        "Portland State University",
        "The University of Texas at Tyler",
        "Angelo State University",
        "East Central University",
        "Southeastern Oklahoma State University",
        "University of Wisconsin",
        " Eau Claire",
        "Northern Michigan University",
        "Xavier University",
        "Colorado College",
        "Keene State College",
        "Harvard university",
        "University of Massachusetts Dartmouth",
        "Brandeis University",
        "Southern Connecticut State University",
        "City College of New York",
        "State University of New York at Oneonta",
        "State University of New York in Brockport",
        "McDaniel College",
        "The College of Idaho",
        "Utah State University",
        "Cameron University",
        "Minnesota State University Moorhead",
        "University of Wisconsin",
        " La Crosse",
        "Indiana University-South Bend",
        "Georgetown University",
        "University of Southern Maine",
        "Missouri Valley College",
        "Western Oregon University",
        "Eastern New Mexico University",
        "Southwestern Oklahoma State University",
        "Wesley College",
        "Idaho State University",
        "University of Colorado at Colorado Springs",
        "West Virginia Institute of Technology",
        "Southern Utah University",
        "Southern New Hampshire University",
        "Utah Valley University",
        "Colorado Mesa University",
        "Virginia Technical University",
        "Binghamton University State University of New York",
        "University of Wisconsin",
        " Parkside",
        "Oregon Institute of Technology",
        "Middlebury College",
        "Cal Poly",
        " SLO",
        "Mississippi State University",
        "University of Texas",
        " San Antonio",
        "Loyola University of New Orleans",
    ];

    public function design_tag_college()
    {
        return $this->list[rand(0, count($this->list) - 1)];
    }
}